tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "inverse-surface": "#dce1fb",
              "error": "#ffb4ab",
              "surface-dim": "#0c1324",
              "on-surface": "#dce1fb",
              "tertiary-fixed-dim": "#abd600",
              "on-tertiary": "#283500",
              "primary-fixed-dim": "#00dce5",
              "surface-bright": "#33394c",
              "on-primary-fixed": "#002021",
              "on-secondary-container": "#6a4800",
              "primary-fixed": "#63f7ff",
              "secondary-fixed": "#ffdeac",
              "on-error": "#690005",
              "surface-container": "#191f31",
              "on-secondary-fixed": "#281900",
              "error-container": "#93000a",
              "on-secondary": "#432c00",
              "outline-variant": "#3a494a",
              "surface-tint": "#00dce5",
              "on-surface-variant": "#b9caca",
              "surface-container-highest": "#2e3447",
              "on-tertiary-fixed": "#161e00",
              "on-error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#3c4d00",
              "surface": "#0c1324",
              "surface-container-high": "#23293c",
              "background": "#0c1324",
              "on-tertiary-container": "#536900",
              "primary": "#e9feff",
              "on-primary": "#003739",
              "inverse-primary": "#00696e",
              "tertiary-fixed": "#c3f400",
              "on-primary-container": "#006c71",
              "surface-container-lowest": "#070d1f",
              "outline": "#849495",
              "secondary-container": "#feb300",
              "secondary": "#ffd799",
              "secondary-fixed-dim": "#ffba38",
              "surface-container-low": "#151b2d",
              "tertiary": "#f6ffd3",
              "inverse-on-surface": "#2a3043",
              "surface-variant": "#2e3447",
              "tertiary-container": "#bfef00",
              "on-secondary-fixed-variant": "#604100",
              "on-background": "#dce1fb",
              "on-primary-fixed-variant": "#004f53",
              "primary-container": "#00f5ff"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Space Grotesk"],
              "body": ["Manrope"],
              "label": ["Space Grotesk"]
      }
    },
  },
}